# Generated by Django 4.1 on 2024-05-12 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("payments", "0002_delete_payment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "txn_id",
                    models.CharField(blank=True, max_length=25, null=True, unique=True),
                ),
                ("transaction_date", models.DateTimeField()),
                ("amount", models.FloatField()),
                (
                    "payment_method",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "amount_status",
                    models.CharField(
                        choices=[("Received", "Received"), ("Refund", "Refund")],
                        default="Received",
                        max_length=25,
                    ),
                ),
                ("refund_to", models.CharField(blank=True, max_length=25, null=True)),
                (
                    "reason_of_refund",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("cancelled_on", models.DateTimeField(blank=True, null=True)),
                ("amount_refund", models.FloatField(blank=True, null=True)),
                (
                    "paid_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
