# Generated by Django 4.1 on 2024-05-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="txn_id",
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
    ]
