# Generated by Django 5.0.6 on 2024-06-08 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_groups_alter_user_user_permissions'),
        ('payments', '0004_alter_transaction_txn_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.user'),
        ),
    ]
