# Generated by Django 4.1 on 2024-05-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("customer", "Customer"),
                    ("member", "Member"),
                    ("admin", "Admin"),
                ],
                default="customer",
                max_length=20,
            ),
        ),
    ]
